using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.IO;
using DevExpress.XtraGrid.Columns;
using System.Data.SqlClient;

namespace DXApplication_1
{
	public partial class GirlListForm : DevExpress.XtraEditors.XtraForm
	{
		public GirlListForm()
		{
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			// Fill a SqlDataSource
			sqlDataSource1.Fill();
		}

		private void GirlForm_Load(object sender, EventArgs e)
		{
			// delete column
			GridColumn delColumn = new GridColumn();
			delColumn.Caption = "Delete";
			delColumn.Visible = true;
			delColumn.ColumnEdit = repositoryItemHyperLinkDel;
			gridView1.Columns.Add(delColumn);

			delColumn.VisibleIndex = 4;
			gridView1.BestFitColumns();

			// edit column
			GridColumn editColumn = new GridColumn();
			editColumn.Caption = "Edit";
			editColumn.Visible = true;
			editColumn.ColumnEdit = repositoryItemHyperLinkEdit;
			gridView1.Columns.Add(editColumn);
			editColumn.VisibleIndex = 5;
			gridView1.BestFitColumns();
		}

		private void gridControl1_Click(object sender, EventArgs e)
		{

		}
		// logout Btn Clicked
		private void simpleButton1_Click(object sender, EventArgs e)
		{
			File.Delete("login.txt");
			LoginForm loginForm = new LoginForm();
			loginForm.ShowDialog();
			this.Close();
		}

		// delete column clicked
		private void repositoryItemHyperLinkDel_Click(object sender, EventArgs e)
		{
			if (MessageBox.Show("Confirm Deletion?","vwhm.net",MessageBoxButtons.OKCancel)==DialogResult.OK)
			{
				// Get Selected Row
				int[] selectedRows = gridView1.GetSelectedRows();
				int selectedIndex = selectedRows[0];
				var idStr = gridView1.GetRowCellValue(selectedIndex, "ID");

				// write sql,  Server=DESKTOP-1G3JHJP;
				var connStr = "server=.;database=db5;Integrated Security=true;";
				SqlConnection conn = new SqlConnection(connStr);
				SqlCommand cmd = conn.CreateCommand();
				cmd.CommandText = "delete from Girl where ID = @ID";
				cmd.Parameters.Clear();
				cmd.Parameters.Add("@ID", idStr);
				conn.Open();
				cmd.ExecuteNonQuery();
				cmd.Dispose();
				conn.Close();
				// refresh data source
				sqlDataSource1.Fill();
			}
		}
		// refresh button clicked
		private void simpleButton3_Click(object sender, EventArgs e)
		{
			// gridControl1.DataSource = list;
			// gridView1.RefreshData();
			sqlDataSource1.Fill();
		}

		// add Btn Clicked
		private void simpleButton2_Click(object sender, EventArgs e)
		{
			// 弹出窗体，新增，保存，刷新
			GirlAddForm addForm = new GirlAddForm();
			addForm.ShowDialog();
			if (addForm.DialogResult == DialogResult.OK) {
				sqlDataSource1.Fill();
			}
		}

		// edit column clicked
		private void repositoryItemHyperLinkEdit_Click(object sender, EventArgs e)
		{
			// get selected Row : ID Age Name
			int[] selectedRows = gridView1.GetSelectedRows();
			int selectedIndex = selectedRows[0];
			var idStr = gridView1.GetRowCellValue(selectedIndex, "ID");
			// bind Data to Edit Form
			// 弹出窗体, Modify，保存，刷新
			GirlEditForm editForm = new GirlEditForm();
			editForm.ID = idStr.ToString();
			editForm.ShowDialog();
			// Wait Edit Form DialogResult and Refresh GridView
			if (editForm.DialogResult == DialogResult.OK)
			{
				sqlDataSource1.Fill();
			}
			
		}
	}
}